"""Render TEAM-STANDARDS.md from core.standards.yml + domain.standards.yml."""

from __future__ import annotations

from pathlib import Path

import jinja2

from py_attest.errors import StandardsDriftError
from py_attest.standards.registry import Registry, load_registry

_TEMPLATE = jinja2.Template(
    "# Team Standards\n\n"
    "<!-- GENERATED by `attest standards build` -- edit domain.standards.yml "
    "(or core.standards.yml), never this file. -->\n\n"
    "All pull requests are reviewed against this document.\n"
    "{% for section in sections %}\n"
    "## {{ loop.index }}. {{ section.title }}\n"
    "{% for rule in section.rules %}\n"
    '- **{{ rule.id }}** ({{ rule.severity or "contextual" }}): {{ rule.title }}. '
    "{{ rule.description.strip() }}\n"
    "{% endfor %}"
    "{% endfor %}\n"
    "## Review severities\n\n"
    "- **S1 -- blocks merge:** severe violations (PII exposure, committed secrets, "
    "data-retention or minimization violations involving minors' data).\n"
    "- **S2 -- blocks merge:** logic bugs that produce incorrect data; core logic "
    "without effective tests.\n"
    "- **S3 -- comment, does not block:** style, naming, refactoring opportunities.\n",
    trim_blocks=True,
    lstrip_blocks=True,
)


def render(registry: Registry) -> str:
    sections = (*registry.core_sections, *registry.domain_sections)
    return _TEMPLATE.render(sections=sections)


def build(core_path: Path, domain_path: Path, output_path: Path, *, check: bool = False) -> str:
    registry = load_registry(core_path, domain_path)
    rendered = render(registry)
    if check:
        existing = output_path.read_text(encoding="utf-8") if output_path.is_file() else None
        if existing != rendered:
            raise StandardsDriftError(
                f"{output_path} is out of date with {core_path.name}/{domain_path.name}; "
                "run `attest standards build` to regenerate"
            )
        return rendered
    output_path.write_text(rendered, encoding="utf-8")
    return rendered
